### ISSUE TITLE
How to install node-webkit app as a daemon using node-mac?

### ISSUE THREAD

**Issue by paolooo** [coreybutler/node-mac#10]
Hello,

Is it possible to install a node-webkit app as a service using node-mac? I've tried to run the ff script:

```
var Service = require('node-mac').Service;

// Create a new service object
var svc = new Service({
  name: 'TestService',
  description: 'Test Service.',
  script: '/path/to/test.app',
});

svc.on('install',function(){
  svc.start(); 
});

svc.install();
```

It register the service successfully but it has some error:

```
module.js:340
    throw err;
          ^
Error: Cannot find module '/path/to/test.app'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

Too many restarts within the last 60 seconds. Please check the script.
```

Any thoughts on how to run a .app or perhaps .exe?

Thanks.

**Comment by fritx** [comment]
+1 for nwjs app

**Comment by fritx** [comment]
oops, great app @coreybutler 
and great solution @paolooo would get a try
