### ISSUE TITLE
Does this need sudo?

### ISSUE THREAD

**Issue by linonetwo** [coreybutler/node-mac#27]
I got

```
Error: EACCES: permission denied, mkdir '/Library/Logs/TiddlyWiki'
    at Object.mkdirSync (fs.js:887:3)
    at daemon.value [as install] (/xxx/node_modules/node-mac/lib/daemon.js:290:9)
```

What should I do If I want this install process more automatic(without prompt for password) Can I change log dir to /tmp ?

**Comment by linonetwo** [comment]
Oh I see, it is in the doc... sorry.

**Comment by coreybutler** [comment]
No worries!
